substitutions:
  device_name: "test-ina226-velux"
  device_friendly: "INA226 Test Rolluik"

esphome:
  name: ${device_name}
  friendly_name: ${device_friendly}

esp32:
  board: esp32s3box
  framework:
    type: arduino

i2c:
  sda: GPIO42
  scl: GPIO41
  scan: true
  frequency: 100kHz

logger:
  level: DEBUG # Zo zie je de I2C scan resultaten

api:
  encryption:
    key: !secret api_encryption_key

ota:
  - platform: esphome
    password: !secret ota_password

# Gebruik de web_server om live de waarden te bekijken zonder HA
web_server:
  port: 80

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  use_address: 192.168.0.28

globals:
  - id: enc1_abs
    type: int
    restore_value: yes
    initial_value: "0"

sensor:
  - platform: ina226
    address: 0x40
    shunt_resistance: 0.1 ohm
    update_interval: 100ms
    current:
      name: "Test Rolluik Stroom"
      id: test_current
    power:
      name: "Test Rolluik Vermogen"

  - platform: pulse_counter
    pin:
      number: GPIO4
      mode: INPUT_PULLUP
      inverted: true      # Velux encoders trekken vaak naar GND (Active Low)
    id: enc1
    name: "Rolluik 1 Pulsen per minuut"
    update_interval: 500ms
    internal_filter: 13us
    on_value:
      then:
        - lambda: |-
            // Voor de test tellen we simpelweg op om te zien of de pulsen binnenkomen
            id(enc1_abs) += (int)x;
            ESP_LOGD("ENCODER", "Totaal aantal pulsen: %d", id(enc1_abs));


# Eenvoudige switches om de motor handmatig te bedienen tijdens het meten
pca9554:
  - id: TCA9554_hub
    address: 0x20

switch:
  - platform: gpio
    pin:
      pca9554: TCA9554_hub
      number: 0
    name: "Relais Omhoog (R1)"
    id: r1_up
    interlock: [r1_down]

  - platform: gpio
    pin:
      pca9554: TCA9554_hub
      number: 1
    name: "Relais Omlaag (R1)"
    id: r1_down
    interlock: [r1_up]

text_sensor:
  - platform: template
    name: "Rolluik 1 Totaal Pulsen"
    lambda: |-
      return str_sprintf("%d", id(enc1_abs));
    update_interval: 1s
